-d F:\TangMega-138K-example\Pro_board\sfp+\impl\gwsynthesis\fpga_project.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst F:\TangMega-138K-example\Pro_board\sfp+\src\fpga_project.cst
-cfg F:\TangMega-138K-example\Pro_board\sfp+\impl\pnr\device.cfg
-sdc F:\TangMega-138K-example\Pro_board\sfp+\src\fpga_project.sdc
-gao_crc 1111111111100011
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-rtl_gao
-csr F:/TangMega-138K-example/Pro_board/sfp+/src/serdes/serdes.csr
