-d G:\TangMega138K\TangMega-138KPro-example\dvi\hdmi\impl\gwsynthesis\hdmi.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst G:\TangMega138K\TangMega-138KPro-example\dvi\hdmi\src\hdmi.cst
-cfg G:\TangMega138K\TangMega-138KPro-example\dvi\hdmi\impl\pnr\device.cfg
-sdc G:\TangMega138K\TangMega-138KPro-example\dvi\hdmi\src\hdmi.sdc
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
