-d C:\Users\zeroh\Desktop\todo\gw138\pro\impl\gwsynthesis\pro.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst C:\Users\zeroh\Desktop\todo\gw138\pro\src\pro.cst
-cfg C:\Users\zeroh\Desktop\todo\gw138\pro\impl\pnr\device.cfg
-sdc C:\Users\zeroh\Desktop\todo\gw138\pro\src\pro.sdc
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
