-d F:\TangMega-138K-example\Pro_board\audio\audio\impl\gwsynthesis\audio.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst F:\TangMega-138K-example\Pro_board\audio\audio\src\audio.cst
-cfg F:\TangMega-138K-example\Pro_board\audio\audio\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
